version: '3'
services:
  video-editor:
    build:
      context: ./agents/video-editor
    container_name: video-editor
    volumes:
    - ./agents/video-editor:/app
    working_dir: /app
    command: python src/video-editor-agent.py
  article:
    build:
      context: ./agents/article
    container_name: article
    volumes:
    - ./agents/article:/app
    working_dir: /app
    command: python src/article-agent.py
